# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.IntegerField()),
                ('tweet_type', models.CharField(max_length=15)),
                ('tweet_text', models.CharField(max_length=150)),
                ('tweet_text2', models.CharField(max_length=150)),
                ('tweet_text_url', models.CharField(max_length=150)),
                ('retweets', models.IntegerField()),
                ('favourites', models.IntegerField()),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('screen_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('profile_pic', models.CharField(max_length=1000)),
                ('followers', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tweets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Users'),
        ),
    ]
