# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170515_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.CharField(max_length=100),
        ),
    ]
